version: '3.1'
services:
  db:
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=user  
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=rufet
    # volumes:
    # - ./mydb/:/var/lib/postgresql/data      
  adminer:
    image: adminer
    ports:
      - 8080:8080   
  redisdb:
    image: redis
    ports:
      - 6379:6379 

