# Generated by Django 4.0.3 on 2022-05-20 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('header', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='detail_product',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
