# Generated by Django 4.0.3 on 2022-04-17 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('header', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='summary',
            field=models.CharField(max_length=40, verbose_name='Summary'),
        ),
    ]
