# Generated by Django 4.0.3 on 2022-05-14 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('header', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail_product',
            name='product_det',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_det', to='header.product'),
        ),
    ]
