# Generated by Django 4.0.4 on 2022-05-17 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('header', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail_product',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
