# Generated by Django 4.0.3 on 2022-04-13 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('header', '0002_alter_review_price_review_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='price_review',
            field=models.SmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=0, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='review',
            name='quality_review',
            field=models.SmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=0, verbose_name='Quality'),
        ),
        migrations.AlterField(
            model_name='review',
            name='summary',
            field=models.CharField(max_length=40, verbose_name='summar'),
        ),
        migrations.AlterField(
            model_name='review',
            name='value_review',
            field=models.SmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=0, verbose_name='Value'),
        ),
    ]
