# Generated by Django 4.0.3 on 2022-05-14 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('header', '0002_alter_detail_product_product_det'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propertyvalues',
            name='abs_ptr',
        ),
        migrations.RemoveField(
            model_name='propertyvalues',
            name='product_detail',
        ),
        migrations.RemoveField(
            model_name='propertyvalues',
            name='property_name',
        ),
        migrations.RenameField(
            model_name='detail_product',
            old_name='product_det',
            new_name='detail',
        ),
        migrations.DeleteModel(
            name='Images',
        ),
        migrations.DeleteModel(
            name='PropertyValues',
        ),
    ]
