# Generated by Django 4.0.3 on 2022-06-27 21:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('header', '0002_alter_product_category_pro'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('abs_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='header.abs')),
                ('subscribers_emails', models.EmailField(max_length=50, unique=True)),
            ],
            bases=('header.abs',),
        ),
    ]
