# Generated by Django 4.0.3 on 2022-06-29 22:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('header', '0003_subscriber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category_pro',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product', to='header.category'),
        ),
    ]
