# Generated by Django 4.0.3 on 2022-05-15 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('header', '0003_remove_propertyvalues_abs_ptr_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail_product',
            name='detail',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_det', to='header.product'),
        ),
        migrations.CreateModel(
            name='PropertyValues',
            fields=[
                ('abs_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='header.abs')),
                ('name', models.CharField(max_length=50)),
                ('product_detail', models.ManyToManyField(db_table='ProductPropertiesValues', to='header.detail_product')),
                ('property_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='propertyvalues', to='header.propertyname')),
            ],
            bases=('header.abs',),
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('abs_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='header.abs')),
                ('images_tb', models.ImageField(upload_to='img/product/images ')),
                ('productsdetail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='header.detail_product')),
            ],
            bases=('header.abs',),
        ),
    ]
