# Generated by Django 4.0.3 on 2022-05-10 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('header', '0003_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product_Detail',
            fields=[
                ('abs_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='header.abs')),
                ('image', models.ImageField(upload_to='img/product')),
                ('desc', models.TextField()),
                ('new_pr', models.CharField(max_length=10)),
                ('old_pr', models.CharField(max_length=10)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('product_det', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='peoduct_det', to='header.product')),
            ],
            bases=('header.abs',),
        ),
    ]
