# Generated by Django 4.0.3 on 2022-03-15 22:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('header', '0004_alter_images_picture_alter_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='tag',
            field=models.ManyToManyField(blank=True, to='header.tag'),
        ),
        migrations.AlterField(
            model_name='images',
            name='haqq',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='header.product'),
        ),
        migrations.DeleteModel(
            name='About',
        ),
    ]
