# Generated by Django 4.0.3 on 2022-05-10 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('header', '0004_product_detail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('abs_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='header.abs')),
                ('images_tb', models.ImageField(upload_to='img/product/images ')),
                ('productsdetail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='header.product_detail')),
            ],
            bases=('header.abs',),
        ),
    ]
