# Generated by Django 4.0.3 on 2022-05-15 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('header', '0004_alter_detail_product_detail_propertyvalues_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category_pro',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product', to='header.category'),
        ),
    ]
