# Generated by Django 4.0.3 on 2022-05-10 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('header', '0005_images'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyName',
            fields=[
                ('abs_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='header.abs')),
                ('name', models.CharField(max_length=40)),
                ('category_base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='propertyname', to='header.category')),
            ],
            bases=('header.abs',),
        ),
    ]
