# Generated by Django 4.0.3 on 2022-03-16 06:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('header', '0005_product_tag_alter_images_haqq_delete_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='haqq',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='header.product'),
        ),
    ]
