# Generated by Django 4.0.3 on 2022-05-10 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('header', '0006_propertyname'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyValues',
            fields=[
                ('abs_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='header.abs')),
                ('name', models.CharField(max_length=50)),
                ('product_detail', models.ManyToManyField(db_table='ProductPropertiesValues', to='header.product_detail')),
                ('property_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='propertyvalues', to='header.propertyname')),
            ],
            bases=('header.abs',),
        ),
    ]
