# Generated by Django 4.0.3 on 2022-03-17 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('header', '0007_alter_images_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='picture',
            field=models.ImageField(upload_to='img/images'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='img/product'),
        ),
    ]
