# Generated by Django 4.0.3 on 2022-04-01 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('header', '0007_alter_product_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='tag',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
