# Generated by Django 4.0.3 on 2022-03-29 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('header', '0008_alter_images_picture_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='picture',
            field=models.ImageField(upload_to='img/images '),
        ),
    ]
