# Generated by Django 4.0.3 on 2022-03-29 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('header', '0009_alter_images_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='tag',
            field=models.ManyToManyField(blank=True, related_name='Product', to='header.tag'),
        ),
    ]
