# Generated by Django 4.0.3 on 2022-05-10 16:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('header', '0009_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='Add_To_Card',
            fields=[
                ('abs_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='header.abs')),
                ('add_product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='add_to_card', to='header.product')),
                ('add_usr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='add_to_card', to=settings.AUTH_USER_MODEL)),
            ],
            bases=('header.abs',),
        ),
    ]
