# Generated by Django 4.0.3 on 2022-04-01 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('header', '0010_alter_product_tag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='images',
            old_name='haqq',
            new_name='products',
        ),
    ]
