# Generated by Django 4.0.4 on 2022-05-11 07:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('header', '0010_add_to_card'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_detail',
            name='product_det',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_det', to='header.product'),
        ),
    ]
