# Generated by Django 4.0.3 on 2022-04-04 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('header', '0011_rename_haqq_images_products'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cont_Info',
            fields=[
                ('abs_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='header.abs')),
                ('fname', models.CharField(max_length=35)),
                ('lname', models.CharField(max_length=35)),
                ('company', models.CharField(max_length=50)),
                ('tel', models.CharField(max_length=13)),
                ('fax', models.CharField(max_length=30)),
                ('s_address', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=35)),
                ('state', models.SmallIntegerField(choices=[(1, 'Alabama'), (2, 'Alaska'), (3, 'Arizona')])),
                ('zip', models.CharField(max_length=25)),
                ('country', models.SmallIntegerField(choices=[(1, 'Azerbaijan'), (2, 'Afganistan')])),
                ('bil_addr', models.BooleanField()),
                ('ship_addr', models.BooleanField()),
            ],
            bases=('header.abs',),
        ),
    ]
