# Generated by Django 4.0.3 on 2022-05-11 21:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('header', '0011_alter_product_detail_product_det'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_detail',
            name='product_det',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_detail', to='header.product'),
        ),
    ]
