# Generated by Django 4.0.3 on 2022-04-05 08:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('header', '0012_cont_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photos_1',
            fields=[
                ('abs_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='header.abs')),
                ('photo1', models.ImageField(upload_to='img/pro/images')),
                ('pro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='header.product')),
            ],
            bases=('header.abs',),
        ),
        migrations.DeleteModel(
            name='Images',
        ),
    ]
