# Generated by Django 4.0.3 on 2022-04-05 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('header', '0015_cont_info_s_2addres_alter_cont_info_s_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cont_info',
            old_name='s_2addres',
            new_name='s_2address',
        ),
    ]
