# Generated by Django 4.0.3 on 2022-04-10 17:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('header', '0017_product_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('abs_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='header.abs')),
                ('comment', models.CharField(max_length=100)),
                ('product_revi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Review', to='header.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Rewiew', to=settings.AUTH_USER_MODEL)),
            ],
            bases=('header.abs',),
        ),
    ]
